[package]
name = "deft-reversi-cli"
version = "0.1.0"
edition = "2021"

[dependencies]
clap = { version = "4.5.23", features = ["derive"] }
deft_reversi_engine = { path = "../deft-reversi-engine" } 
rand = "0.8.5"
